### PR TITLE
Chore: Apply useful patches from upstream

### PR DESCRIPTION
**Pull request by stumpylog**
This PR applies the following PRs from the upstream project to here:

- https://github.com/Koed00/django-q/pull/603
- https://github.com/Koed00/django-q/pull/604
- https://github.com/Koed00/django-q/pull/605
- https://github.com/Koed00/django-q/pull/423
- https://github.com/Koed00/django-q/pull/659

These bring in a few bug fixes and enhancements, as well as a few QoL changes.  It doesn't fix any issues I know of paperless users encountering, but you never know.

All tests still pass, and the paperless image built to include this branch (at 81f96395609c665654c64b51988b090fc705e534) didn't have any problems.

### CODE REVIEW

**Comment by stumpylog** [comment]
@paperless-ngx/backend 

When folks have some time, I've applied a few patches from upstream to review.  I believe this will help [#1355](https://github.com/paperless-ngx/paperless-ngx/issues/1355) at the least

**Review by shamoon — APPROVED** [review]
Oh I didn’t see this, nice! Not sure if you feel this needs specific testing since they were merged upstream?

**Comment by stumpylog** [comment]
None of them have merged upstream. I just grabbed the patches for some pending PRs which looked useful.

I've tested an image with this version and it worked normally from what I could tell.  Plus the existing test suite passes

**Comment by qcasey** [comment]
Thanks for the work on this and #2, stumpylog. I imagine we will do beta tests for v1.8.1. Would you like to target these two PRs for that release?

Nothing in the code looks blatantly wrong to me but I can't say much beyond that.

**Pull request merged**
