### PR TITLE
Feature: Adds the ability to set the process title for things like top or ps

### PR DESCRIPTION
**Pull request by stumpylog**
### Previous Architecture

The previous code did not attempt to set process titles at all, leading to tools showing multiple `python3 manage.py document_consumer` commands running and under each other in the tree.

### New Architecture

With the changes in this PR, the various processes spawned by django-q will be named in tools like `top` or `ps` if `setproctitle` is installed.

image

#### Considerations

This will slightly increase the Docker image size, but will not affect users who have installed via the bare metal route.  In the future, the worker number and the worker generation could also be included, for at a glance information concerning how many  workers are spawned, and how many times they have died or been recycled.

### CODE REVIEW

**Comment by shamoon** [comment]
Am I correct that testing this should just be similar to the other i.e. update the pipfile and install? Even with that my `top` just shows `Python` as the process, Im on macOS btw. But I believe you this works =)

**Comment by stumpylog** [comment]
Similar, but different ha. In this case, the `setproctitle` is optional, so it's not installed by default and would need to be added to the Pipfile separately.

**Comment by shamoon** [comment]
Ah that makes sense, ok so still just `Python` for me but I bet its something about my setup / how Im testing...

**Review by shamoon — APPROVED** [review]
This seems pretty straightforward even if I cant figure out how to properly test

**Comment by shamoon** [comment]
@stumpylog also not sure if you want to merge a few more of these so we can get into 1.9.0 (and test in beta)?

**Comment by stumpylog** [comment]
Yeah, I'll merge this one, as it's very safe.  The others though, if we're moving to celery, I'll leave out or move to my own fork.

**Pull request merged**
